# Generated by Django 2.2.19 on 2021-03-20 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='issued_at',
            field=models.DateTimeField(default=datetime.datetime.utcnow, help_text='Date time after wich tokens are valid .', verbose_name='issued at'),
        ),
    ]
