# Generated by Django 2.2.19 on 2021-03-21 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210320_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeniedToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('token', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denied_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'denied_token',
            },
        ),
    ]
