# Generated by Django 2.2.19 on 2021-03-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_deniedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deniedtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
